### ISSUE TITLE
Error in ambari_trigger_service_checks.py

### ISSUE THREAD

**Issue by chitralverma** [HariSekhon/pytools#3]
Im trying to execute ambari_trigger_service_checks.py but it is failing on line 44

`Traceback (most recent call last):
  File "./ambari_trigger_service_checks.py", line 53, in <module>
    from harisekhon.utils import log, die, support_msg_api, code_error, isInt, isList, jsonpp
ImportError: No module named harisekhon.utils`

EDIT:: I got the utils.py from your other repo but im running into a lot of dependency issues. 

Please assist me with this

**Comment by HariSekhon** [comment]
You haven't read the README on the main page underneath the code.

The build instructions say not to try to copy things out, just git clone and cd and run "make". It'll get all the dependencies for you automatically.

In that case you just haven't got the python requests module installed.

**Comment by HariSekhon** [comment]
I'm going to close this issue as this is simply a case of not having built the project as per the instructions on the main page in the README.md.

If you need you can re-open this issue is there is anything else (after you have read and followed the documented instructions! ;)  )
